# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab6.proto',
  package='lab6',
  syntax='proto3',
  serialized_options=_b('\n\025io.grpc.examples.lab6B\tLab6ProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\nlab6.proto\x12\x04lab6\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"\x17\n\x08imageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32^\n\x08lab6GRPC\x12%\n\x03\x61\x64\x64\x12\x0c.lab6.addMsg\x1a\x0e.lab6.addReply\"\x00\x12+\n\x05image\x12\x0e.lab6.imageMsg\x1a\x10.lab6.imageReply\"\x00\x42*\n\x15io.grpc.examples.lab6B\tLab6ProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_ADDMSG = _descriptor.Descriptor(
  name='addMsg',
  full_name='lab6.addMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='lab6.addMsg.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='lab6.addMsg.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_ADDREPLY = _descriptor.Descriptor(
  name='addReply',
  full_name='lab6.addReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='lab6.addReply.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=75,
)


_IMAGEMSG = _descriptor.Descriptor(
  name='imageMsg',
  full_name='lab6.imageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='lab6.imageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=100,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='imageReply',
  full_name='lab6.imageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='lab6.imageReply.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='lab6.imageReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['addMsg'] = _ADDMSG
DESCRIPTOR.message_types_by_name['addReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['imageMsg'] = _IMAGEMSG
DESCRIPTOR.message_types_by_name['imageReply'] = _IMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addMsg = _reflection.GeneratedProtocolMessageType('addMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.addMsg)
  })
_sym_db.RegisterMessage(addMsg)

addReply = _reflection.GeneratedProtocolMessageType('addReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.addReply)
  })
_sym_db.RegisterMessage(addReply)

imageMsg = _reflection.GeneratedProtocolMessageType('imageMsg', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.imageMsg)
  })
_sym_db.RegisterMessage(imageMsg)

imageReply = _reflection.GeneratedProtocolMessageType('imageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6.imageReply)
  })
_sym_db.RegisterMessage(imageReply)


DESCRIPTOR._options = None

_LAB6GRPC = _descriptor.ServiceDescriptor(
  name='lab6GRPC',
  full_name='lab6.lab6GRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='lab6.lab6GRPC.add',
    index=0,
    containing_service=None,
    input_type=_ADDMSG,
    output_type=_ADDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='image',
    full_name='lab6.lab6GRPC.image',
    index=1,
    containing_service=None,
    input_type=_IMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAB6GRPC)

DESCRIPTOR.services_by_name['lab6GRPC'] = _LAB6GRPC

# @@protoc_insertion_point(module_scope)
